/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekuas;

import com.mysql.cj.protocol.Resultset;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class master_supplier extends javax.swing.JFrame {

    /**
     * Creates new form master_supplier
     */
    public master_supplier() {
        initComponents();
        tampilkandata();
        hapuskolom();
    }
    
    public void tampilkandata()
    {
        try
        {   Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas_jam_tangan", "root", "");
    
            String url = "SELECT * FROM master_supplier";
            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(url);
            
            DefaultTableModel model = (DefaultTableModel) tabel_mastersupplier.getModel();
            model.setRowCount(0);
            
            while (rs.next())
            {
                String kode_supplier = rs.getString("kode_supplier");
                String nama_supplier = rs.getString("nama_supplier");
                String alamat = rs.getString("alamat");
                String nomor_telepon = rs.getString("nomor_telepon");
                
                Object[] data = {kode_supplier, nama_supplier, alamat, nomor_telepon};
                model.addRow(data);
            }
        }
        catch (Exception e)
        {
            
        }
    }
    
    public void hapuskolom()
    {
        kd.setText("");
        ns.setText("");
        nt.setText("");
        a.setText("");
        kolomcari.setText("");
    }
    
    public void filterangkanomortelepon(KeyEvent a)
    {
        if (Character.isDigit(a.getKeyChar()))
        {
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nomor telepon hanya bisa mengisi angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
            a.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_barang = new javax.swing.JPanel();
        kd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        judul_input_barang = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_mastersupplier = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        kolomcari = new javax.swing.JTextField();
        judul_input_barang1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        judul_input_barang3 = new javax.swing.JLabel();
        judul_input_barang4 = new javax.swing.JLabel();
        judul_input_barang5 = new javax.swing.JLabel();
        judul_input_barang8 = new javax.swing.JLabel();
        judul_input_barang9 = new javax.swing.JLabel();
        judul_input_barang10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_barang.setBackground(new java.awt.Color(255, 255, 255));

        kd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText(" Kode Supplier");

        ns.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText(" Nama Supplier");

        nt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntActionPerformed(evt);
            }
        });
        nt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ntKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText(" Alamat");

        a.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText(" Nomor Telepon");

        judul_input_barang.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        judul_input_barang.setText("Input Supplier");

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tabel_mastersupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Supplier", "Nama Supplier", "Nomor Telepon", "Alamat"
            }
        ));
        tabel_mastersupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_mastersupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_mastersupplier);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Cari Supplier :");

        kolomcari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kolomcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomcariActionPerformed(evt);
            }
        });
        kolomcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kolomcariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolomcariKeyTyped(evt);
            }
        });

        judul_input_barang1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        judul_input_barang1.setText("Tabel Data Supplier");

        javax.swing.GroupLayout input_barangLayout = new javax.swing.GroupLayout(input_barang);
        input_barang.setLayout(input_barangLayout);
        input_barangLayout.setHorizontalGroup(
            input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_barangLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(input_barangLayout.createSequentialGroup()
                        .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ns, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judul_input_barang1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judul_input_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(input_barangLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(input_barangLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kolomcari, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_barangLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_barangLayout.createSequentialGroup()
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_barangLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        input_barangLayout.setVerticalGroup(
            input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_barangLayout.createSequentialGroup()
                .addComponent(judul_input_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ns, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul_input_barang1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolomcari, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(input_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 820, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul_input_barang3.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang3.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang3.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang3.setText("H");
        jPanel2.add(judul_input_barang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 70));

        judul_input_barang4.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang4.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang4.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang4.setText("E");
        jPanel2.add(judul_input_barang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 60));

        judul_input_barang5.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang5.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang5.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang5.setText("L");
        jPanel2.add(judul_input_barang5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 60));

        judul_input_barang8.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang8.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang8.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang8.setText("D");
        jPanel2.add(judul_input_barang8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, 60));

        judul_input_barang9.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang9.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang9.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang9.setText("H");
        jPanel2.add(judul_input_barang9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 180, 60));

        judul_input_barang10.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang10.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang10.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang10.setText("I");
        jPanel2.add(judul_input_barang10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 180, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 600));

        jMenu8.setText("Menu");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu1.setText("Transaksi");

        jMenuItem1.setText("Penjualan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Pembelian");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laporan");

        jMenu5.setText("Penjualan");

        jMenuItem5.setText("Rinci");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem7.setText("Kasar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu2.add(jMenu5);

        jMenu6.setText("Pembelian");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Master");

        jMenuItem10.setText("Supplier");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Petugas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem3.setText("Barang");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Log Out");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1014, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed

    }//GEN-LAST:event_aActionPerformed

    private void kdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdActionPerformed
        ns.grabFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_kdActionPerformed

    private void nsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsActionPerformed
        nt.grabFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_nsActionPerformed

    private void ntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntActionPerformed
        a.grabFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_ntActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            String url = "INSERT INTO master_supplier (kode_supplier, nama_supplier, alamat, nomor_telepon) VALUES (?, ?, ?, ?)";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas_jam_tangan", "root", "");
    
            PreparedStatement pst = conn.prepareStatement(url);
            
            pst.setString(1, kd.getText());
            pst.setString(2, ns.getText());
            pst.setString(3, nt.getText());
            pst.setString(4, a.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data supplier berhasil ditambah");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Data supplier gagal ditambah " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        tampilkandata();
        hapuskolom();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabel_mastersupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_mastersupplierMouseClicked
        int baris = tabel_mastersupplier.rowAtPoint(evt.getPoint());
        
        String kode_supplier = tabel_mastersupplier.getValueAt(baris, 0).toString();
        kd.setText(kode_supplier);
        
        String nama_supplier = tabel_mastersupplier.getValueAt(baris, 1).toString();
        ns.setText(nama_supplier);
 
        String alamat = tabel_mastersupplier.getValueAt(baris, 2).toString();
        nt.setText(alamat);
        
        String nomor_telepon = tabel_mastersupplier.getValueAt(baris, 3).toString();
        a.setText(nomor_telepon);
    }//GEN-LAST:event_tabel_mastersupplierMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try {    
        String sql = "UPDATE master_supplier SET kode_supplier=?, nama_supplier=?, alamat=?, nomor_telepon=? WHERE kode_supplier = '"+kd.getText()+"'";
        java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas_jam_tangan", "root", "");
    
        java.sql.PreparedStatement pst=conn.prepareStatement(sql);
        pst.setString(1, kd.getText());
        pst.setString(2, ns.getText());
        pst.setString(3, nt.getText());
        pst.setString(4, a.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil perbarui","Informasi",JOptionPane.INFORMATION_MESSAGE);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Data gagal diperbarui" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
}   
        tampilkandata();
        hapuskolom();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    kd.setText("");
     ns.setText(""); nt.setText("");  a.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            String url = "DELETE FROM master_supplier WHERE kode_supplier = '"+kd.getText()+"'";
;           java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas_jam_tangan", "root", "");
    
            java.sql.PreparedStatement pst = conn.prepareStatement(url);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data supplier berhasil dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Data supplier gagal dihapus "+ e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        tampilkandata();
        hapuskolom();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyTyped
       
    }//GEN-LAST:event_aKeyTyped

    private void kolomcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomcariActionPerformed

    }//GEN-LAST:event_kolomcariActionPerformed

    private void kolomcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomcariKeyTyped
       

    }//GEN-LAST:event_kolomcariKeyTyped

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
      
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
      
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
       
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
      
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new master_supplier().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
       
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
       
    }//GEN-LAST:event_jMenu7MouseClicked

    private void ntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ntKeyTyped
     filterangkanomortelepon(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_ntKeyTyped

    private void kolomcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomcariKeyReleased
    try
        {
          

            String sql = "SELECT * FROM master_supplier WHERE nama_supplier LIKE '%"+kolomcari.getText()+"%' OR kode_supplier LIKE '%"+kolomcari.getText()+"%' OR alamat LIKE '%"+kolomcari.getText()+"%' OR nomor_telepon LIKE '%"+kolomcari.getText()+"%'";
            java.sql.Connection conn = (Connection)config.inputbarang();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            java.sql.ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tabel_mastersupplier.getModel();
            model.setRowCount(0);

            
            while (rs.next())
            {
                String kode_barang = rs.getString("kode_supplier");
                String nama_barang = rs.getString("nama_supplier");
                String warna = rs.getString("alamat");
                String gender = rs.getString("nomor_telepon");

                Object[] data = {kode_barang, nama_barang, warna, gender};
                model.addRow(data);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_kolomcariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(master_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(master_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(master_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(master_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new master_supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JPanel input_barang;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judul_input_barang;
    private javax.swing.JLabel judul_input_barang1;
    private javax.swing.JLabel judul_input_barang10;
    private javax.swing.JLabel judul_input_barang3;
    private javax.swing.JLabel judul_input_barang4;
    private javax.swing.JLabel judul_input_barang5;
    private javax.swing.JLabel judul_input_barang8;
    private javax.swing.JLabel judul_input_barang9;
    private javax.swing.JTextField kd;
    private javax.swing.JTextField kolomcari;
    private javax.swing.JTextField ns;
    private javax.swing.JTextField nt;
    private javax.swing.JTable tabel_mastersupplier;
    // End of variables declaration//GEN-END:variables
}
