/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekuas;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.AccessibleObject;
import java.lang.reflect.Method;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Base64;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class penjualan extends javax.swing.JFrame {

     private DecimalFormat decimalFormat;
    /**
     * Creates new form penjualan
     */
    public penjualan() {
        initComponents();
        tampilkanetalase();
    }
    
    public void tampilkanetalase()
    {
        try
        {
            String url = "SELECT * FROM stok";
            Connection con = config.inputbarang();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(url);
            
            DefaultTableModel model = (DefaultTableModel) etalase.getModel();
            model.setRowCount(0);
            
            int no = 1;
            while (rs.next())
            {

                String kodebarang = rs.getString("kodebarang");
                String namabarang = rs.getString("namabarang");
                String warna = rs.getString("warna");
                String gender = rs.getString("gender");
                String harga = rs.getString("harga");
                String jumlah = rs.getString("jumlah");
                
                Object[] data = {kodebarang, namabarang, warna, gender, harga, jumlah};
                model.addRow(data);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        etalase = new javax.swing.JTable();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        hargatotal2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        uangbayar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        labelnomorfaktur = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        judul_input_barang3 = new javax.swing.JLabel();
        judul_input_barang4 = new javax.swing.JLabel();
        judul_input_barang5 = new javax.swing.JLabel();
        judul_input_barang8 = new javax.swing.JLabel();
        judul_input_barang9 = new javax.swing.JLabel();
        judul_input_barang10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        kolomcari1 = new javax.swing.JTextField();
        kodebarang = new javax.swing.JLabel();
        namabarang = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        warna = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        hargajual = new javax.swing.JLabel();
        stoktersedia = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelfoto = new javax.swing.JLabel();
        nomorfaktur = new javax.swing.JTextField();
        subtotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keranjang = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        hargatotal = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();

        jDialog1.setBackground(new java.awt.Color(255, 255, 255));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etalase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Warna", "Gender", "Harga", "Stok Tersisa"
            }
        ));
        etalase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etalaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(etalase);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 300));

        jDialog1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 300));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hargatotal2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        hargatotal2.setText("0");
        jPanel4.add(hargatotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 20, 320, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Uang Bayar");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 40));

        uangbayar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        uangbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uangbayarKeyReleased(evt);
            }
        });
        jPanel4.add(uangbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Kembalian");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 40));

        kembalian.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jPanel4.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, 40));

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BAYAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 140, 50));

        labelnomorfaktur.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jPanel4.add(labelnomorfaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 50));

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton6)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jButton6)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul_input_barang3.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang3.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang3.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang3.setText("H");
        jPanel2.add(judul_input_barang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 70));

        judul_input_barang4.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang4.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang4.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang4.setText("E");
        jPanel2.add(judul_input_barang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 60));

        judul_input_barang5.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang5.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang5.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang5.setText("L");
        jPanel2.add(judul_input_barang5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 60));

        judul_input_barang8.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang8.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang8.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang8.setText("D");
        jPanel2.add(judul_input_barang8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, 60));

        judul_input_barang9.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang9.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang9.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang9.setText("H");
        jPanel2.add(judul_input_barang9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 180, 60));

        judul_input_barang10.setBackground(new java.awt.Color(255, 255, 255));
        judul_input_barang10.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        judul_input_barang10.setForeground(new java.awt.Color(255, 255, 255));
        judul_input_barang10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_input_barang10.setText("I");
        jPanel2.add(judul_input_barang10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 180, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Barang", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kolomcari1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kolomcari1MouseClicked(evt);
            }
        });
        kolomcari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomcari1ActionPerformed(evt);
            }
        });
        kolomcari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kolomcari1KeyReleased(evt);
            }
        });
        jPanel5.add(kolomcari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 28));

        kodebarang.setBackground(new java.awt.Color(0, 0, 0));
        kodebarang.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        kodebarang.setText("-");
        jPanel5.add(kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 151, 40));

        namabarang.setBackground(new java.awt.Color(0, 0, 0));
        namabarang.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        namabarang.setText("-");
        jPanel5.add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 250, 40));

        gender.setBackground(new java.awt.Color(0, 0, 0));
        gender.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gender.setText("-");
        jPanel5.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 260, 40));

        warna.setBackground(new java.awt.Color(0, 0, 0));
        warna.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        warna.setText("-");
        jPanel5.add(warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 40));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 17, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("- Kode Barang     =");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 140, 40));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("- Harga Jual          =");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 40));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 40));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 40));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("- Nama Barang     =");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 40));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("- Warna                 =");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 40));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setText("- Gender               =");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 40));

        hargajual.setBackground(new java.awt.Color(0, 0, 0));
        hargajual.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hargajual.setText("-");
        jPanel5.add(hargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 280, 40));

        stoktersedia.setBackground(new java.awt.Color(0, 0, 0));
        stoktersedia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        stoktersedia.setText("-");
        jPanel5.add(stoktersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 280, 40));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("- Stok Tersedia    =");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 270));

        labelfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(labelfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 18, 340, 280));

        nomorfaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorfakturActionPerformed(evt);
            }
        });
        jPanel1.add(nomorfaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 290, 240, 31));

        subtotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        subtotal.setText("0");
        jPanel1.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 264, -1));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton2.setText("TAMBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 110, 40));

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton5.setText("BATAL");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 110, 40));

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton4.setText("BAYAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 117, 40));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("- Nomor Faktur");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, -1));

        keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No. Faktur", "Tanggal", "Nama Barang", "Kode Barang", "Warna", "Harga Jual", "Qty", "Sub Total"
            }
        ));
        jScrollPane2.setViewportView(keranjang);
        if (keranjang.getColumnModel().getColumnCount() > 0) {
            keranjang.getColumnModel().getColumn(0).setMaxWidth(50);
            keranjang.getColumnModel().getColumn(7).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 420, 780, 120));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("- Jumlah Dibeli");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, -1));

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 330, 240, 31));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("- Tanggal Penjualan");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 170, 40));

        hargatotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        hargatotal.setText("0");
        jPanel1.add(hargatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 264, -1));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kolomcari1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kolomcari1MouseClicked
        jDialog1.setSize(810, 210);
        jDialog1.setLocationRelativeTo(null);
        int dx = 90;
        int dy = 30; // Jarak vertikal ke bawah dalam piksel (misalnya, 50 piksel)
        jDialog1.setLocation(jDialog1.getX() + dx, jDialog1.getY() + dy);

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setVisible(true);
        kolomcari1.requestFocus();    // TODO add your handling code here:
    }//GEN-LAST:event_kolomcari1MouseClicked

    private void kolomcari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomcari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomcari1ActionPerformed

    private void kolomcari1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomcari1KeyReleased

    }//GEN-LAST:event_kolomcari1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomorfakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorfakturActionPerformed

    }//GEN-LAST:event_nomorfakturActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    DefaultTableModel tbl = (DefaultTableModel) keranjang.getModel();
        String nomorfaktur1 = nomorfaktur.getText();
        String kodebarang1 = (String) kodebarang.getText();
        String namabarang1 = namabarang.getText();
        String warna1 = (String) warna.getText();
        String gender1 = gender.getText();
        int JumlahBarang1 = Integer.parseInt(jumlah.getText());
        int hargajual1 = Integer.parseInt(hargajual.getText());
        String subtotal1 = subtotal.getText().toString().replace("Rp", "").replace(".", "").replace(",", "");
        String t = tanggal.getDateFormatString();
        
        int subtotal2 = JumlahBarang1 * hargajual1;
        
        DefaultTableModel model = (DefaultTableModel) keranjang.getModel();
        int rowCount = model.getRowCount();
        int noUrut = rowCount + 1;
        labelfoto.getIcon();
        Date tanggalInput = tanggal.getDate();
         String formatInput = "dd MMMM yyyy";
                String formatOutput = "dd/MM/yy";
                SimpleDateFormat inputDateFormat = new SimpleDateFormat(formatInput);
                SimpleDateFormat outputDateFormat = new SimpleDateFormat(formatOutput);
                String tanggalOutput = outputDateFormat.format(tanggalInput);
                

                Icon icon = labelfoto.getIcon();
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                BufferedImage bufferedImage = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics2D g2d = bufferedImage.createGraphics();
                g2d.drawImage(((ImageIcon) icon).getImage(), 0, 0, null);
                g2d.dispose();
                try {
                    ImageIO.write(bufferedImage, "png", baos);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                byte[] imageBytes = baos.toByteArray();
                try {
                    baos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
    String textIcon = Base64.getEncoder().encodeToString(imageBytes);
    Object[] row = {noUrut, nomorfaktur1, tanggalOutput, namabarang1, kodebarang1, warna1, hargajual1, JumlahBarang1, subtotal2};
    model.addRow(row);
    
    // menghitung jumlah/harga total bozzz
        int totalHarga = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            String subTotal = model.getValueAt(i, 8).toString();
            int jumlahSubTotal = Integer.valueOf(subTotal);
            totalHarga += jumlahSubTotal;
        }
        
        DecimalFormat formatter = new DecimalFormat("###,###");
        hargatotal.setText("Rp " + formatter.format(totalHarga));
        hargatotal2.setText("Rp " + formatter.format(totalHarga));
        
    // menghapus / clear
    kodebarang.setText("-");
    namabarang.setText("-");
    warna.setText("-");
    gender.setText("-");
    hargajual.setText("-");
    stoktersedia.setText("-");
    jumlah.setText("");
    tanggal.setDate(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void etalaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etalaseMouseClicked
        int baris = etalase.rowAtPoint(evt.getPoint());

        String kode_barang = etalase.getValueAt(baris, 0).toString();
        kodebarang.setText(kode_barang);

        String nama_barang = etalase.getValueAt(baris, 1).toString();
        namabarang.setText(nama_barang);

        String warna1 = etalase.getValueAt(baris, 2).toString();
        warna.setText(warna1);

        String gender1 = etalase.getValueAt(baris, 3).toString();
        gender.setText(gender1);
        
        String harga1 = etalase.getValueAt(baris, 4).toString();
        hargajual.setText(harga1);
        
        String jumlah1 = etalase.getValueAt(baris, 5).toString();
        stoktersedia.setText(jumlah1);
        
        jDialog1.setVisible(false);
        kolomcari1.setText("");
        
        etalase.clearSelection();
        kolomcari1.requestFocus();
        
        try {
    // Memeriksa isi Label1 sebelum mengambil dan menampilkan foto
    if (!kodebarang.getText().equals("-")) {
        // Menghubungkan ke database
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas_jam_tangan", "root", "");

       String sql = "SELECT gambar FROM master_barang WHERE kode_barang = ?";
       PreparedStatement statement = connection.prepareStatement(sql);
       statement.setString(1, kodebarang.getText()); // Menggunakan getText() untuk mendapatkan teks dari kodebarang
       ResultSet result = statement.executeQuery();

        if (result.next()) {
                // Mengambil data gambar dari hasil query
                Blob fotoBlob = result.getBlob("gambar");
                byte[] fotoBytes = fotoBlob.getBytes(1, (int) fotoBlob.length());

                // Menampilkan gambar di label
                BufferedImage image = ImageIO.read(new ByteArrayInputStream(fotoBytes));
                ImageIcon icon = new ImageIcon(image);
                labelfoto.setIcon(icon);

            // Menutup stream dan koneksi
            statement.close();
            connection.close();
        }
    }
} catch (SQLException e) {
    e.printStackTrace();
} catch (IOException e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_etalaseMouseClicked

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        if (jumlah.getText().equals("")){
        subtotal.setText("0");}
        else{
        String text1 = hargajual.getText();
        double amount1 = Double.parseDouble(text1.replaceAll("[^\\d.]", ""));

        String text2 = jumlah.getText();
        double amount2 = Double.parseDouble(text2.replaceAll("[^\\d.]", ""));

        double result = amount1 * amount2;
        
        DecimalFormat decimalFormat = new DecimalFormat("#,###");

        String formattedResult = decimalFormat.format(result);
        subtotal.setText("Rp "+formattedResult);} // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
    Connection con = config.inputbarang();
    DefaultTableModel model = (DefaultTableModel) keranjang.getModel();
    
    String sql = "INSERT INTO laporan_penjualan (nomor_faktur, tanggal, kode_barang, nama_barang, warna, harga_jual, qty, sub_total, harga_total) VALUES (?,?,?,?,?,?,?,?,?)";
    PreparedStatement pst = con.prepareStatement(sql);
    
    int totalHarga = 0;
    
    for (int row = 0; row < model.getRowCount(); row++) {
        String nomorfaktur = model.getValueAt(row, 1).toString();
        String tanggal = model.getValueAt(row, 2).toString();
        String kodebarang = model.getValueAt(row, 4).toString();
        String namabarang = model.getValueAt(row, 3).toString();
        String warna = model.getValueAt(row, 5).toString();
        String hargajual = model.getValueAt(row, 6).toString();
        String qty = model.getValueAt(row, 7).toString();
        String subtotal = model.getValueAt(row, 8).toString();
        
        int subtotalInt = Integer.parseInt(subtotal);
        totalHarga += subtotalInt;
        
        // Kurangi stok di tabel "stok"
        String updateStokQuery = "UPDATE stok SET jumlah = jumlah - ? WHERE kodebarang = ?";
        PreparedStatement updateStokStatement = con.prepareStatement(updateStokQuery);
        updateStokStatement.setString(1, qty);
        updateStokStatement.setString(2, kodebarang);
        updateStokStatement.executeUpdate();
        
        pst.setString(1, nomorfaktur);
        pst.setString(2, tanggal);
        pst.setString(3, kodebarang);
        pst.setString(4, namabarang);
        pst.setString(5, warna);
        pst.setString(6, hargajual);
        pst.setString(7, qty);
        pst.setString(8, subtotal);
        pst.setString(9, String.valueOf(totalHarga));
        
        pst.executeUpdate();
    }
    model.setRowCount(0);
    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
    
    jDialog2.dispose();
    
            jDialog3.setSize(400, 300);
        jDialog3.setLocationByPlatform(true);

            
        jDialog3.setLocationRelativeTo(null);
        int dx = 90;
        int dy = 30; // Jarak vertikal ke bawah dalam piksel (misalnya, 50 piksel)
        jDialog3.setLocation(jDialog3.getX() + dx, jDialog3.getY() + dy);
            
        jDialog3.setVisible(true);
        
        labelnomorfaktur.setText(nomorfaktur.getText());
            
} catch (Exception e) {
    e.printStackTrace();
}


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jDialog2.setSize(400, 300);
        jDialog2.setLocationByPlatform(true);

            
        jDialog2.setLocationRelativeTo(null);
        int dx = 90;
        int dy = 30; // Jarak vertikal ke bawah dalam piksel (misalnya, 50 piksel)
        jDialog2.setLocation(jDialog2.getX() + dx, jDialog2.getY() + dy);
            
        jDialog2.setVisible(true);
        
        labelnomorfaktur.setText(nomorfaktur.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void uangbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangbayarKeyReleased
        DefaultTableModel model = (DefaultTableModel) keranjang.getModel();
        int totalHarga = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            String subTotal = model.getValueAt(i, 8).toString();
            int jumlahSubTotal = Integer.valueOf(subTotal);
            totalHarga += jumlahSubTotal;
        }
        
        int uangbayar1 = Integer.valueOf(uangbayar.getText());
        
        int uangkembalian = uangbayar1 - totalHarga;
        DecimalFormat formatter = new DecimalFormat("###,###");
        kembalian.setText("Rp " + formatter.format(uangkembalian));

    }//GEN-LAST:event_uangbayarKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            String NamaFile = "./src/projekuas/penjualan.jasper";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/uas_jam_tangan","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("nomor_faktur",nomorfaktur.getText());
                   
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint);
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable etalase;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel hargajual;
    private javax.swing.JLabel hargatotal;
    private javax.swing.JLabel hargatotal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judul_input_barang10;
    private javax.swing.JLabel judul_input_barang3;
    private javax.swing.JLabel judul_input_barang4;
    private javax.swing.JLabel judul_input_barang5;
    private javax.swing.JLabel judul_input_barang8;
    private javax.swing.JLabel judul_input_barang9;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTable keranjang;
    private javax.swing.JLabel kodebarang;
    private javax.swing.JTextField kolomcari1;
    private javax.swing.JLabel labelfoto;
    private javax.swing.JLabel labelnomorfaktur;
    private javax.swing.JLabel namabarang;
    private javax.swing.JTextField nomorfaktur;
    private javax.swing.JLabel stoktersedia;
    private javax.swing.JLabel subtotal;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField uangbayar;
    private javax.swing.JLabel warna;
    // End of variables declaration//GEN-END:variables
}
